### ISSUE TITLE
'0' converts to ''

### ISSUE THREAD

**Issue by Darkster1** [clark800/bigint-base-converter#4] opened 2021-10-18 17:26 UTC
convertBase('0', '0123456789abcdef', 'fedcba9876543210') converts to ''.
converting any 0 prefixed string has expected output f prefixed
"0000123" "fffff..."
as it does for convertBase('ffff', '0123456789abcdef', 'fedcba9876543210') returns expected "0000".

**Comment by clark800** [comment] 2021-11-08 20:24
Thanks for the bug report. I fixed the issue of '0' converting to ''. I couldn't reproduce the part about "converting any 0 prefixed string has expected output f prefixed". `convertBase('0000123', '0123456789abcdef', 'fedcba9876543210')` produces `edc`. Please let me know if the issue is fixed or if there is another test case that fails.

**Comment by Darkster1** [comment] 2021-11-21 02:00
I see, the 0 -> '' is fixed.
About the other thing, for example if you want to use convertBase to "inverse" a hex string (there are other easier ways but to display the example);
the inverse of 'ffffffffffffffff' is: '00000...' using: convertBase('ffffffff','0123456789abcdef','fedcba9876543210');
Doing the same convertBase( ... ,'0123456789abcdef','fedcba9876543210'); but then for '0000000' expected output ffffffff, current output: 'f' (single).
It's not really a big issue, but I can imagine a few things where it would be very handy for. But I leave it up to you wheater to 'fix' it or add it as an optional feature.
Thanks anyways!

**Comment by clark800** [comment] 2021-11-23 17:13
Ok, the second part is not an intended feature, so I'll close this.

**Closed as completed by clark800** 2021-11-23 17:13 UTC
